---
# This playbook deploys the whole application stack in this site.  

- name: apply common configuration to all nodes
  hosts: all
  remote_user: vagrant

  roles:
    - common

- name: configure and deploy the webservers and application code
  hosts: devserver
  remote_user: vagrant

  roles:
    - web
    - db
    - joshualund.golang
    - dev
